name: 07c - Additional Secret Demo Workflow

on: [workflow_dispatch]

jobs:
  demo_secrets_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Secret Validation
        env:
          MY_SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          # Check if secret is set without exposing it
          if [ -n "$MY_SECRET_MESSAGE" ]; then
            echo "✅ Secret is properly configured"
          else
            echo "⚠️ Secret is not set - PLEASE SET UP MY_SECRET_MESSAGE IN REPOSITORY SETTINGS"
            echo "Go to Settings → Secrets and variables → Actions → New repository secret"
          fi

      - name: Demo Secret Usage
        if: ${{ env.MY_SECRET_MESSAGE != '' }}
        env:
          MY_SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Example of using secret securely
          echo "🔒 Using secret securely in script"
          # Simulate using secret without printing it
          echo "Secret length: ${#MY_SECRET_MESSAGE} characters"
          echo "The built-in GITHUB_TOKEN is automatically available: ${GITHUB_TOKEN != ''}"
