name: 01b - Hello World with Inputs

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'Student'
      greet:
        description: 'Namethe greetings'
        required: true
        default: 'Good Morning'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello, ${{ github.event.inputs.name }} . ${{ github.event.inputs.greet }}!"
