name: 01b - Hello World with Inputs

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
:
        description: 'Name of the person to greet'
        required: true

jobs:
  greet:
    runs-on      name:
        description: 'Name of the person to greet'
        required: true

jobs:
  greet:
    runs: ubuntu-latest-on: ubuntu-latest
    steps:
      - name:
    steps:
      - name: Send greeting Send greeting
        run: echo "Hello ${{ github.event
        run: echo "Hello ${{ github.event.inputs.name ||.inputs.name || ' 'GitHub Actions' }}!"
      
      - name: Show dateGitHub Actions' }}!"
      
      - name: Show date
        run: |
          echo "
        run: |
          echo "Current date isCurrent date is $(date)"
          echo "This job runs on ${{ runner.os }}"
      
      - name: Print GitHub context
        run: echo "${{ toJson(github) }}"
      
      - name: List GitHub context
        run $(date)"
          echo "This job runs on $: echo "${{ toJson(github) }}" | jq .
